[flexpart_data]
git-tree-sha1 = "beb6adaed9b183279f08651ebf0fad00b524db19"

    [[flexpart_data.download]]
    sha256 = "ecbbcda79981975bd9b68f7732da00ff8cfb4aa0e950ea3c94431888120bd891"
    url = "https://github.com/tcarion/flexpart_data/archive/refs/tags/v0.2.0.tar.gz"
